#Create a playbook /home/automation/plays/repository.yml that runs on servers in the database host group and does the following:
#
#A YUM repository file is created.
#The name of the repository is mysql56-community.
#The description of the repository is “MySQL 5.6 YUM Repo”.
#Repository baseurl is http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/.
#Repository GPG key is at http://repo.mysql.com/RPM-GPG-KEY-mysql.
#Repository GPG check is enabled.
#Repository is enabled.
#command used => ansible-playbook 8_repository.yml
##########################################################################
#
---
- hosts: database
  gather_facts: false
  become: true
  tasks:
    - name: Adding mysql56-community Repository on database hosts group
      yum_repository:
        name: mysql56-community
        description: MySQL 5.6 YUM Repo
        baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
      tags: add_mysql_repo  


    - shell: yum repolist
      register: yumlist

    - debug: 
        var: yumlist.stdout_lines          

...
