# Task 15: Work with Ansible Facts
# Create a playbook /home/automation/plays/facts.yml that runs on hosts in the database host group and does the following:
# 
# A custom Ansible fact server_role=mysql is created that can be retrieved from ansible_local.custom.sample_exam when using Ansible setup module.
# 
# Do as follows 
# Command used => ansible-playbook 15_ansible_facts.yml
---
- hosts: database
  become: true
  gather_facts: true
  tasks:
    - name: Creating /etc/ansible/facts.d/ directory
      file: path=/etc/ansible/facts.d/ state=directory

    - name: copying custom.fact file 
      copy: 
          src: custom.fact
          dest: /etc/ansible/facts.d/custom.fact 


    - debug:
        msg: ansible_local.custom.sample_exam is "{{ ansible_local.custom.sample_exam }}"     


    - debug:
        var: ansible_local.custom.sample_exam
        
...
